// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEmployee.Data;

#nullable disable

namespace MvcEmployee.Migrations
{
    [DbContext(typeof(MvcEmployeeContext))]
    [Migration("20230127124802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MvcEmployee.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("MvcEmployee.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenderId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("MvcEmployee.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("QualificationListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("QualificationListId");

                    b.ToTable("Qualification");
                });

            modelBuilder.Entity("MvcEmployee.Models.QualificationList", b =>
                {
                    b.Property<int>("QualificationListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationListId");

                    b.ToTable("QualificationList");
                });

            modelBuilder.Entity("MvcEmployee.Models.Gender", b =>
                {
                    b.HasOne("MvcEmployee.Models.Employee", null)
                        .WithMany("Gender")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("MvcEmployee.Models.Qualification", b =>
                {
                    b.HasOne("MvcEmployee.Models.Employee", "Employee")
                        .WithMany("Qualification")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcEmployee.Models.QualificationList", "QualificationList")
                        .WithMany()
                        .HasForeignKey("QualificationListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("QualificationList");
                });

            modelBuilder.Entity("MvcEmployee.Models.Employee", b =>
                {
                    b.Navigation("Gender");

                    b.Navigation("Qualification");
                });
#pragma warning restore 612, 618
        }
    }
}
